version: 2
multi-ecosystem-groups:
  shakapacker:
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      semver-patch-days: 5
      semver-minor-days: 10
      semver-major-days: 15
    groups:
      rubocop:
        patterns:
          - "rubocop*"
    ignore:
      - dependency-name: rails
        versions: ">= 7.0.0"
      - dependency-name: rspec-rails
        versions: ">= 7.0.0"
      - dependency-name: turbo-rails
        versions: ">= 2.0.13"
    patterns:
      - "shakapacker"
    multi-ecosystem-group: shakapacker
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      semver-patch-days: 5
      semver-minor-days: 10
      semver-major-days: 15
    groups:
      babel:
        patterns:
          - "@babel/*"
      fontawesome:
        patterns:
          - "@fortawesome/*"
      rails:
        patterns:
          - "@rails/*"
      webpack:
        patterns:
          - "webpack*"
    ignore:
      - dependency-name: "@rails/*"
        versions: ">= 7.0.0"
    patterns:
      - "shakapacker"
    multi-ecosystem-group: shakapacker
