version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      rubocop:
        patterns:
          - "rubocop*"
    ignore:
      - dependency-name: rails
        versions: ">= 7.0.0"
      - dependency-name: rspec-rails
        versions: ">= 7.0.0"
      - dependency-name: turbo-rails
        versions: ">= 2.0.13"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      babel:
        patterns:
          - "@babel/*"
      fontawesome:
        patterns:
          - "@fortawesome/*"
      rails:
        patterns:
          - "@rails/*"
      webpack:
        patterns:
          - "webpack*"
    ignore:
      - dependency-name: "@rails/*"
        versions: ">= 7.0.0"
      - dependency-name: "@types/express"
        versions: ">= 5.0.0"
